language: node_js

node_js:
  - "iojs"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run cov

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
