os:
  - linux
language: node_js
node_js:
  - "4.1"
  - "0.12"
branches:
  only:
    - dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  email:
    - kuvakin@gmail.com
install:
  - export CXX=g++-4.8
  - npm install
  - npm run build
